workflows:
  flutter-build:
    name: Build Flutter App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          cd l_r_drones_app
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd l_r_drones_app/ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
      - name: Build APK
        script: |
          cd l_r_drones_app
          flutter build apk --debug
      - name: Build iOS
        script: |
          cd l_r_drones_app
          flutter build ios --debug
    artifacts:
      - l_r_drones_app/build/**/outputs/**/*.apk