workflows:
  flutter-build:
    name: Build Flutter App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get dependencies
        script: |
          cd l_r_drones_app
          flutter pub get

      - name: Clean CocoaPods
        script: |
          cd l_r_drones_app/ios
          rm -rf Pods
          rm -rf Podfile.lock
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/.cocoapods/repos
          pod deintegrate
          pod setup
          pod repo update


      - name: Build Android (APK e AAB)
        script: |
          cd l_r_drones_app
          flutter build apk --debug
          flutter build appbundle --debug

      - name: Install CocoaPods
        script: |
          cd l_r_drones_app/ios
          pod install


      - name: Build iOS
        script: |
          cd l_r_drones_app
          flutter build ios --debug

    artifacts:
      - l_r_drones_app/build/**/outputs/**/*.apk
      - l_r_drones_app/build/**/outputs/**/*.aab
      - l_r_drones_app/build/ios/ipa/*.ipa